id: A837993AA
base_file: f847E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:30:48.711319
  last_modified_at: 2022-06-19 17:30:48.711327
