id: A837993AA
base_file: fB94A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:30:48.720352
  last_modified_at: 2022-06-19 17:30:48.720364
