id: A837993AA
base_file: f44F4.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:30:48.698355
  last_modified_at: 2022-06-19 17:30:48.698365
