id: A837993AA
base_file: f7C4E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:30:48.708529
  last_modified_at: 2022-06-19 17:30:48.708541
