id: A837993AA
base_file: fF224.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:30:48.732532
  last_modified_at: 2022-06-19 17:30:48.732542
